version: '3'

services:
  resources:
    build: './resources'
    links:
      - "models"
      - "database"

  models:
    build: './models'
    links:
      - "database"

  database:
    build: "./database"

  main:
    build: .
    ports:
      - "5000:5000"
    links:
      - "resources"
